import type { MishanaerIconName } from "./MishanaerIcon";
import {
  MishanaerIcon,
  type MishanaerIconComponent,
  type MishanaerIconProps,
} from "./MishanaerIcon";

export type AppIconProps = Omit<MishanaerIconProps, "name" | "variant">;
export type AppIconComponent = MishanaerIconComponent;

function strokeIcon(name: MishanaerIconName): AppIconComponent {
  const Icon = (props: AppIconProps) => <MishanaerIcon name={name} variant="stroke" {...props} />;
  Icon.displayName = `MishanaerIcon(${name})`;
  return Icon;
}

export const BookOpenIcon = strokeIcon("book-open");
export const MessageSquareIcon = strokeIcon("chat-bubble");
export const BotIcon = strokeIcon("robot");
export const NotebookPenIcon = strokeIcon("pencil-square");
export const UserIcon = strokeIcon("person");
export const PlusIcon = strokeIcon("plus");
export const SearchIcon = strokeIcon("magnifying-glass");
export const XIcon = strokeIcon("x");
export const SortAscIcon = strokeIcon("funnel");
export const ChevronRightIcon = strokeIcon("chevron-right");
export const ChevronLeftIcon = strokeIcon("chevron-left");
export const FolderIcon = strokeIcon("folder");
export const FolderPlusIcon = strokeIcon("folder-plus");
export const FolderInputIcon = strokeIcon("file-plus");
export const MoreVerticalIcon = strokeIcon("dots-three-vertical");
export const BrainIcon = strokeIcon("microchip");
export const ScrollTextIcon = strokeIcon("file-txt");
export const LightbulbIcon = strokeIcon("lightbulb");
export const HistoryIcon = strokeIcon("history");
export const MessageCirclePlusIcon = strokeIcon("chat-bubbles");
export const PaletteIcon = strokeIcon("palette");
export const RefreshCwIcon = strokeIcon("repeat");
export const CloudIcon = strokeIcon("cloud");
export const DatabaseIcon = strokeIcon("database");
export const Volume2Icon = strokeIcon("volume-2");
export const HeadphonesIcon = strokeIcon("headphones");
export const PlayIcon = strokeIcon("play");
export const PauseIcon = strokeIcon("pause");
export const SquareIcon = strokeIcon("stop");
export const RotateCcwIcon = strokeIcon("arrow-rotate-ccw-up");
export const SkipBackIcon = strokeIcon("skip-backward");
export const SkipForwardIcon = strokeIcon("skip-forward");
export const LanguagesIcon = strokeIcon("translate");
export const CpuIcon = strokeIcon("microchip");
export const PuzzleIcon = strokeIcon("puzzle-piece");
export const HelpCircleIcon = strokeIcon("question-circle");
export const InfoIcon = strokeIcon("question-circle");
export const BarChart3Icon = strokeIcon("chart-bar");
export const ClockIcon = strokeIcon("clock-3h");
export const FlameIcon = strokeIcon("flame");
export const TrendingUpIcon = strokeIcon("trending-up");
export const TrophyIcon = strokeIcon("trophy");
export const SwordsIcon = strokeIcon("shield");
export const HighlighterIcon = strokeIcon("paint-roller");
export const CopyIcon = strokeIcon("copy");
export const Trash2Icon = strokeIcon("bin");
export const TagIcon = strokeIcon("tag");
export const CheckCheckIcon = strokeIcon("checks");
export const SparklesIcon = strokeIcon("sparkles");
export const LoaderIcon = strokeIcon("pulse-circle");
export const Loader2Icon = strokeIcon("pulse-circle");
export const WrenchIcon = strokeIcon("wrench");
export const HashIcon = strokeIcon("hash");
export const ArrowDownAZIcon = strokeIcon("arrow-down");
export const ArrowUpAZIcon = strokeIcon("arrow-up");
export const SendIcon = strokeIcon("arrow-block-up");
export const StopCircleIcon = strokeIcon("stop");
export const OctagonXIcon = strokeIcon("x-hexagon");
export const ChevronDownIcon = strokeIcon("chevron-down");
export const ChevronUpIcon = strokeIcon("chevron-up");
export const CheckIcon = strokeIcon("check");
export const EditIcon = strokeIcon("pencil");
export const ShareIcon = strokeIcon("share-network");
export const FilterIcon = strokeIcon("funnel");
export const CalendarIcon = strokeIcon("calendar");
export const SwitchIcon = strokeIcon("arrows-left-right");
export const SunIcon = strokeIcon("sun");
export const MoonIcon = strokeIcon("crescent");
export const Undo2Icon = strokeIcon("arrow-rotate-ccw-up");
export const Redo2Icon = strokeIcon("arrow-rotate-cw-up");
export const EyeIcon = strokeIcon("eye");
export const EyeOffIcon = strokeIcon("eye-slash");
export const BoldIcon = strokeIcon("text-b");
export const BoldIcon2 = BoldIcon;
export const ItalicIcon = strokeIcon("text-i");
export const StrikethroughIcon = strokeIcon("strikethrough");
export const ListIcon = strokeIcon("list");
export const ListOrderedIcon = strokeIcon("list-alt1");
export const CodeIcon = strokeIcon("code");
export const Link2Icon = strokeIcon("link");
export const QuoteIcon = strokeIcon("quote-left");
export const MinusIcon = strokeIcon("minus");
export const Heading1Icon = strokeIcon("text-t");
export const Heading2Icon = strokeIcon("text-t");
export const Heading3Icon = strokeIcon("text-t");
export const LibraryIcon = strokeIcon("books-spines");
export const ZoomIn = strokeIcon("magnifying-glass-plus");
export const ZoomOut = strokeIcon("magnifying-glass-minus");
export const Download = strokeIcon("arrow-to-line-down");
export const RotateCcw = strokeIcon("arrow-rotate-ccw-up");
export const Maximize2 = strokeIcon("corners");
export const Minimize2 = strokeIcon("corners-in");
export const BookmarkIcon = strokeIcon("bookmark");
export const BookmarkFilledIcon = strokeIcon("bookmark");
export const TypeIcon = strokeIcon("text-t");
export const LinkIcon = strokeIcon("link");
export const GlobeIcon = strokeIcon("globe");
export const LayersIcon = strokeIcon("layers");
export const FolderMinusIcon = strokeIcon("folder-minus");

export const AlertCircle = strokeIcon("exclamation-triangle");
export const Bot = BotIcon;
export const Bug = strokeIcon("bug");
export const Check = CheckIcon;
export const CheckCircle2 = strokeIcon("check-circle");
export const ChevronLeft = ChevronLeftIcon;
export const Cloud = CloudIcon;
export const Coffee = strokeIcon("coffee-cup");
export const ExternalLink = strokeIcon("arrow-from-square-up-right");
export const Eye = EyeIcon;
export const EyeOff = EyeOffIcon;
export const Languages = LanguagesIcon;
export const Lightbulb = LightbulbIcon;
export const MessageCircle = strokeIcon("chat-bubble");
export const MessageSquare = MessageSquareIcon;
export const Moon = MoonIcon;
export const Plus = PlusIcon;
export const Scan = strokeIcon("qr-code");
export const Search = SearchIcon;
export const Star = strokeIcon("star");
export const Sun = SunIcon;
export const Trash2 = Trash2Icon;
export const X = XIcon;

export { MishanaerIcon } from "./MishanaerIcon";
export type { MishanaerIconName, MishanaerIconProps } from "./MishanaerIcon";
