// Generated by scripts/sync-mishanaer-icons.mjs. Do not edit by hand.
import type { ImageSourcePropType } from "react-native";
import FilledArrowRotateCcwUpAsset from "../../../assets/icons/mishanaer/filled/arrow-rotate-ccw-up.svg";
import FilledBellAsset from "../../../assets/icons/mishanaer/filled/bell.svg";
import FilledBinAsset from "../../../assets/icons/mishanaer/filled/bin.svg";
import FilledBookAsset from "../../../assets/icons/mishanaer/filled/book.svg";
import FilledChatBubbleAsset from "../../../assets/icons/mishanaer/filled/chat-bubble.svg";
import FilledChatBubblesAsset from "../../../assets/icons/mishanaer/filled/chat-bubbles.svg";
import FilledCloudAsset from "../../../assets/icons/mishanaer/filled/cloud.svg";
import FilledHeadphonesAsset from "../../../assets/icons/mishanaer/filled/headphones.svg";
import FilledMagnifyingGlassAsset from "../../../assets/icons/mishanaer/filled/magnifying-glass.svg";
import FilledPencilSquareAsset from "../../../assets/icons/mishanaer/filled/pencil-square.svg";
import FilledPersonAsset from "../../../assets/icons/mishanaer/filled/person.svg";
import FilledStopAsset from "../../../assets/icons/mishanaer/filled/stop.svg";
import StrokeArchiveAsset from "../../../assets/icons/mishanaer/stroke/archive.svg";
import StrokeArrowBlockUpAsset from "../../../assets/icons/mishanaer/stroke/arrow-block-up.svg";
import StrokeArrowDownAsset from "../../../assets/icons/mishanaer/stroke/arrow-down.svg";
import StrokeArrowFromSquareUpRightAsset from "../../../assets/icons/mishanaer/stroke/arrow-from-square-up-right.svg";
import StrokeArrowLeftRightAsset from "../../../assets/icons/mishanaer/stroke/arrow-left-right.svg";
import StrokeArrowLeftAsset from "../../../assets/icons/mishanaer/stroke/arrow-left.svg";
import StrokeArrowRightAsset from "../../../assets/icons/mishanaer/stroke/arrow-right.svg";
import StrokeArrowRotateCcwUpAsset from "../../../assets/icons/mishanaer/stroke/arrow-rotate-ccw-up.svg";
import StrokeArrowRotateCwUpAsset from "../../../assets/icons/mishanaer/stroke/arrow-rotate-cw-up.svg";
import StrokeArrowToLineDownAsset from "../../../assets/icons/mishanaer/stroke/arrow-to-line-down.svg";
import StrokeArrowUpAsset from "../../../assets/icons/mishanaer/stroke/arrow-up.svg";
import StrokeArrowsLeftRightAsset from "../../../assets/icons/mishanaer/stroke/arrows-left-right.svg";
import StrokeBattery0PercentAsset from "../../../assets/icons/mishanaer/stroke/battery-0percent.svg";
import StrokeBattery25PercentAsset from "../../../assets/icons/mishanaer/stroke/battery-25percent.svg";
import StrokeBattery50PercentAsset from "../../../assets/icons/mishanaer/stroke/battery-50percent.svg";
import StrokeBattery75PercentAsset from "../../../assets/icons/mishanaer/stroke/battery-75percent.svg";
import StrokeBattery100PercentAsset from "../../../assets/icons/mishanaer/stroke/battery-100percent.svg";
import StrokeBatteryChargingAsset from "../../../assets/icons/mishanaer/stroke/battery-charging.svg";
import StrokeBellAsset from "../../../assets/icons/mishanaer/stroke/bell.svg";
import StrokeBinAsset from "../../../assets/icons/mishanaer/stroke/bin.svg";
import StrokeBookOpenMagnifyingGlassAsset from "../../../assets/icons/mishanaer/stroke/book-open-magnifying-glass.svg";
import StrokeBookOpenAsset from "../../../assets/icons/mishanaer/stroke/book-open.svg";
import StrokeBookAsset from "../../../assets/icons/mishanaer/stroke/book.svg";
import StrokeBookmarkAsset from "../../../assets/icons/mishanaer/stroke/bookmark.svg";
import StrokeBooksSpinesAsset from "../../../assets/icons/mishanaer/stroke/books-spines.svg";
import StrokeBugAsset from "../../../assets/icons/mishanaer/stroke/bug.svg";
import StrokeCalendarAsset from "../../../assets/icons/mishanaer/stroke/calendar.svg";
import StrokeCameraAsset from "../../../assets/icons/mishanaer/stroke/camera.svg";
import StrokeChartBarAsset from "../../../assets/icons/mishanaer/stroke/chart-bar.svg";
import StrokeChartLineAsset from "../../../assets/icons/mishanaer/stroke/chart-line.svg";
import StrokeChatBubbleAsset from "../../../assets/icons/mishanaer/stroke/chat-bubble.svg";
import StrokeChatBubblesAsset from "../../../assets/icons/mishanaer/stroke/chat-bubbles.svg";
import StrokeCheckCircleAsset from "../../../assets/icons/mishanaer/stroke/check-circle.svg";
import StrokeCheckAsset from "../../../assets/icons/mishanaer/stroke/check.svg";
import StrokeChecksAsset from "../../../assets/icons/mishanaer/stroke/checks.svg";
import StrokeChevronDownAsset from "../../../assets/icons/mishanaer/stroke/chevron-down.svg";
import StrokeChevronLeftAsset from "../../../assets/icons/mishanaer/stroke/chevron-left.svg";
import StrokeChevronRightAsset from "../../../assets/icons/mishanaer/stroke/chevron-right.svg";
import StrokeChevronSmallRightAsset from "../../../assets/icons/mishanaer/stroke/chevron-small-right.svg";
import StrokeChevronUpAsset from "../../../assets/icons/mishanaer/stroke/chevron-up.svg";
import StrokeClipboardAsset from "../../../assets/icons/mishanaer/stroke/clipboard.svg";
import StrokeClock3hAsset from "../../../assets/icons/mishanaer/stroke/clock-3h.svg";
import StrokeCloudAsset from "../../../assets/icons/mishanaer/stroke/cloud.svg";
import StrokeCodeAsset from "../../../assets/icons/mishanaer/stroke/code.svg";
import StrokeCoffeeCupAsset from "../../../assets/icons/mishanaer/stroke/coffee-cup.svg";
import StrokeCopyAsset from "../../../assets/icons/mishanaer/stroke/copy.svg";
import StrokeCornersInAsset from "../../../assets/icons/mishanaer/stroke/corners-in.svg";
import StrokeCornersAsset from "../../../assets/icons/mishanaer/stroke/corners.svg";
import StrokeCrescentAsset from "../../../assets/icons/mishanaer/stroke/crescent.svg";
import StrokeDatabaseAsset from "../../../assets/icons/mishanaer/stroke/database.svg";
import StrokeDiamondAsset from "../../../assets/icons/mishanaer/stroke/diamond.svg";
import StrokeDotsThreeHorizontalAsset from "../../../assets/icons/mishanaer/stroke/dots-three-horizontal.svg";
import StrokeDotsThreeVerticalAsset from "../../../assets/icons/mishanaer/stroke/dots-three-vertical.svg";
import StrokeExclamationCircleAsset from "../../../assets/icons/mishanaer/stroke/exclamation-circle.svg";
import StrokeExclamationTriangleAsset from "../../../assets/icons/mishanaer/stroke/exclamation-triangle.svg";
import StrokeEyeSlashAsset from "../../../assets/icons/mishanaer/stroke/eye-slash.svg";
import StrokeEyeAsset from "../../../assets/icons/mishanaer/stroke/eye.svg";
import StrokeFilePlusAsset from "../../../assets/icons/mishanaer/stroke/file-plus.svg";
import StrokeFileTxtAsset from "../../../assets/icons/mishanaer/stroke/file-txt.svg";
import StrokeFlameAsset from "../../../assets/icons/mishanaer/stroke/flame.svg";
import StrokeFolderMinusAsset from "../../../assets/icons/mishanaer/stroke/folder-minus.svg";
import StrokeFolderPlusAsset from "../../../assets/icons/mishanaer/stroke/folder-plus.svg";
import StrokeFolderAsset from "../../../assets/icons/mishanaer/stroke/folder.svg";
import StrokeFunnelAsset from "../../../assets/icons/mishanaer/stroke/funnel.svg";
import StrokeGearAsset from "../../../assets/icons/mishanaer/stroke/gear.svg";
import StrokeGlobeAsset from "../../../assets/icons/mishanaer/stroke/globe.svg";
import StrokeGrid2x2Asset from "../../../assets/icons/mishanaer/stroke/grid-2x2.svg";
import StrokeHandAsset from "../../../assets/icons/mishanaer/stroke/hand.svg";
import StrokeHashAsset from "../../../assets/icons/mishanaer/stroke/hash.svg";
import StrokeHeadphonesAsset from "../../../assets/icons/mishanaer/stroke/headphones.svg";
import StrokeHistoryAsset from "../../../assets/icons/mishanaer/stroke/history.svg";
import StrokeImageAsset from "../../../assets/icons/mishanaer/stroke/image.svg";
import StrokeItalicAsset from "../../../assets/icons/mishanaer/stroke/italic.svg";
import StrokeLayersAsset from "../../../assets/icons/mishanaer/stroke/layers.svg";
import StrokeLightbulbAsset from "../../../assets/icons/mishanaer/stroke/lightbulb.svg";
import StrokeLinkAsset from "../../../assets/icons/mishanaer/stroke/link.svg";
import StrokeListAlt1Asset from "../../../assets/icons/mishanaer/stroke/list-alt1.svg";
import StrokeListAsset from "../../../assets/icons/mishanaer/stroke/list.svg";
import StrokeLockLockedAsset from "../../../assets/icons/mishanaer/stroke/lock-locked.svg";
import StrokeMagicWandAsset from "../../../assets/icons/mishanaer/stroke/magic-wand.svg";
import StrokeMagnifyingGlassMinusAsset from "../../../assets/icons/mishanaer/stroke/magnifying-glass-minus.svg";
import StrokeMagnifyingGlassPlusAsset from "../../../assets/icons/mishanaer/stroke/magnifying-glass-plus.svg";
import StrokeMagnifyingGlassAsset from "../../../assets/icons/mishanaer/stroke/magnifying-glass.svg";
import StrokeMicAsset from "../../../assets/icons/mishanaer/stroke/mic.svg";
import StrokeMicrochipAsset from "../../../assets/icons/mishanaer/stroke/microchip.svg";
import StrokeMinusCircleAsset from "../../../assets/icons/mishanaer/stroke/minus-circle.svg";
import StrokeMinusAsset from "../../../assets/icons/mishanaer/stroke/minus.svg";
import StrokeNoteAsset from "../../../assets/icons/mishanaer/stroke/note.svg";
import StrokePaintRollerAsset from "../../../assets/icons/mishanaer/stroke/paint-roller.svg";
import StrokePaletteAsset from "../../../assets/icons/mishanaer/stroke/palette.svg";
import StrokePaperclipAsset from "../../../assets/icons/mishanaer/stroke/paperclip.svg";
import StrokePaperplaneAsset from "../../../assets/icons/mishanaer/stroke/paperplane.svg";
import StrokePauseAsset from "../../../assets/icons/mishanaer/stroke/pause.svg";
import StrokePencilSquareAsset from "../../../assets/icons/mishanaer/stroke/pencil-square.svg";
import StrokePencilAsset from "../../../assets/icons/mishanaer/stroke/pencil.svg";
import StrokePeopleAsset from "../../../assets/icons/mishanaer/stroke/people.svg";
import StrokePersonCircleAsset from "../../../assets/icons/mishanaer/stroke/person-circle.svg";
import StrokePersonAsset from "../../../assets/icons/mishanaer/stroke/person.svg";
import StrokePinAsset from "../../../assets/icons/mishanaer/stroke/pin.svg";
import StrokePlayAsset from "../../../assets/icons/mishanaer/stroke/play.svg";
import StrokePlusCircleAsset from "../../../assets/icons/mishanaer/stroke/plus-circle.svg";
import StrokePlusAsset from "../../../assets/icons/mishanaer/stroke/plus.svg";
import StrokePulseCircleAsset from "../../../assets/icons/mishanaer/stroke/pulse-circle.svg";
import StrokePuzzlePieceAsset from "../../../assets/icons/mishanaer/stroke/puzzle-piece.svg";
import StrokeQrCodeAsset from "../../../assets/icons/mishanaer/stroke/qr-code.svg";
import StrokeQuestionCircleAsset from "../../../assets/icons/mishanaer/stroke/question-circle.svg";
import StrokeQuoteLeftAsset from "../../../assets/icons/mishanaer/stroke/quote-left.svg";
import StrokeRepeatAsset from "../../../assets/icons/mishanaer/stroke/repeat.svg";
import StrokeReplyAsset from "../../../assets/icons/mishanaer/stroke/reply.svg";
import StrokeRobotAsset from "../../../assets/icons/mishanaer/stroke/robot.svg";
import StrokeScalesOfJusticeAsset from "../../../assets/icons/mishanaer/stroke/scales-of-justice.svg";
import StrokeSealCheckAsset from "../../../assets/icons/mishanaer/stroke/seal-check.svg";
import StrokeShareNetworkAsset from "../../../assets/icons/mishanaer/stroke/share-network.svg";
import StrokeShieldAsset from "../../../assets/icons/mishanaer/stroke/shield.svg";
import StrokeSkipBackwardAsset from "../../../assets/icons/mishanaer/stroke/skip-backward.svg";
import StrokeSkipForwardAsset from "../../../assets/icons/mishanaer/stroke/skip-forward.svg";
import StrokeSmileyHappyAsset from "../../../assets/icons/mishanaer/stroke/smiley-happy.svg";
import StrokeSparklesAsset from "../../../assets/icons/mishanaer/stroke/sparkles.svg";
import StrokeStarAsset from "../../../assets/icons/mishanaer/stroke/star.svg";
import StrokeStopAsset from "../../../assets/icons/mishanaer/stroke/stop.svg";
import StrokeStrikethroughAsset from "../../../assets/icons/mishanaer/stroke/strikethrough.svg";
import StrokeSunAsset from "../../../assets/icons/mishanaer/stroke/sun.svg";
import StrokeTagAsset from "../../../assets/icons/mishanaer/stroke/tag.svg";
import StrokeTextBAsset from "../../../assets/icons/mishanaer/stroke/text-b.svg";
import StrokeTextIAsset from "../../../assets/icons/mishanaer/stroke/text-i.svg";
import StrokeTextTAsset from "../../../assets/icons/mishanaer/stroke/text-t.svg";
import StrokeTranslateAsset from "../../../assets/icons/mishanaer/stroke/translate.svg";
import StrokeTrendingUpAsset from "../../../assets/icons/mishanaer/stroke/trending-up.svg";
import StrokeTrophyAsset from "../../../assets/icons/mishanaer/stroke/trophy.svg";
import StrokeVolume2Asset from "../../../assets/icons/mishanaer/stroke/volume-2.svg";
import StrokeWrenchAsset from "../../../assets/icons/mishanaer/stroke/wrench.svg";
import StrokeXHexagonAsset from "../../../assets/icons/mishanaer/stroke/x-hexagon.svg";
import StrokeXAsset from "../../../assets/icons/mishanaer/stroke/x.svg";

export const strokeIconComponents = {
  archive: StrokeArchiveAsset,
  "arrow-block-up": StrokeArrowBlockUpAsset,
  "arrow-down": StrokeArrowDownAsset,
  "arrow-from-square-up-right": StrokeArrowFromSquareUpRightAsset,
  "arrow-left": StrokeArrowLeftAsset,
  "arrow-left-right": StrokeArrowLeftRightAsset,
  "arrow-right": StrokeArrowRightAsset,
  "arrow-rotate-ccw-up": StrokeArrowRotateCcwUpAsset,
  "arrow-rotate-cw-up": StrokeArrowRotateCwUpAsset,
  "arrow-to-line-down": StrokeArrowToLineDownAsset,
  "arrow-up": StrokeArrowUpAsset,
  "arrows-left-right": StrokeArrowsLeftRightAsset,
  "battery-0%": StrokeBattery0PercentAsset,
  "battery-25%": StrokeBattery25PercentAsset,
  "battery-50%": StrokeBattery50PercentAsset,
  "battery-75%": StrokeBattery75PercentAsset,
  "battery-100%": StrokeBattery100PercentAsset,
  "battery-charging": StrokeBatteryChargingAsset,
  bell: StrokeBellAsset,
  bin: StrokeBinAsset,
  book: StrokeBookAsset,
  "book-open": StrokeBookOpenAsset,
  "book-open-magnifying-glass": StrokeBookOpenMagnifyingGlassAsset,
  bookmark: StrokeBookmarkAsset,
  "books-spines": StrokeBooksSpinesAsset,
  bug: StrokeBugAsset,
  calendar: StrokeCalendarAsset,
  camera: StrokeCameraAsset,
  "chart-bar": StrokeChartBarAsset,
  "chart-line": StrokeChartLineAsset,
  "chat-bubble": StrokeChatBubbleAsset,
  "chat-bubbles": StrokeChatBubblesAsset,
  check: StrokeCheckAsset,
  "check-circle": StrokeCheckCircleAsset,
  checks: StrokeChecksAsset,
  "chevron-down": StrokeChevronDownAsset,
  "chevron-left": StrokeChevronLeftAsset,
  "chevron-right": StrokeChevronRightAsset,
  "chevron-small-right": StrokeChevronSmallRightAsset,
  "chevron-up": StrokeChevronUpAsset,
  clipboard: StrokeClipboardAsset,
  "clock-3h": StrokeClock3hAsset,
  cloud: StrokeCloudAsset,
  code: StrokeCodeAsset,
  "coffee-cup": StrokeCoffeeCupAsset,
  copy: StrokeCopyAsset,
  corners: StrokeCornersAsset,
  "corners-in": StrokeCornersInAsset,
  crescent: StrokeCrescentAsset,
  database: StrokeDatabaseAsset,
  diamond: StrokeDiamondAsset,
  "dots-three-horizontal": StrokeDotsThreeHorizontalAsset,
  "dots-three-vertical": StrokeDotsThreeVerticalAsset,
  "exclamation-circle": StrokeExclamationCircleAsset,
  "exclamation-triangle": StrokeExclamationTriangleAsset,
  eye: StrokeEyeAsset,
  "eye-slash": StrokeEyeSlashAsset,
  "file-plus": StrokeFilePlusAsset,
  "file-txt": StrokeFileTxtAsset,
  flame: StrokeFlameAsset,
  folder: StrokeFolderAsset,
  "folder-minus": StrokeFolderMinusAsset,
  "folder-plus": StrokeFolderPlusAsset,
  funnel: StrokeFunnelAsset,
  gear: StrokeGearAsset,
  globe: StrokeGlobeAsset,
  "grid-2x2": StrokeGrid2x2Asset,
  hand: StrokeHandAsset,
  hash: StrokeHashAsset,
  headphones: StrokeHeadphonesAsset,
  history: StrokeHistoryAsset,
  image: StrokeImageAsset,
  italic: StrokeItalicAsset,
  layers: StrokeLayersAsset,
  lightbulb: StrokeLightbulbAsset,
  link: StrokeLinkAsset,
  list: StrokeListAsset,
  "list-alt1": StrokeListAlt1Asset,
  "lock-locked": StrokeLockLockedAsset,
  "magic-wand": StrokeMagicWandAsset,
  "magnifying-glass": StrokeMagnifyingGlassAsset,
  "magnifying-glass-minus": StrokeMagnifyingGlassMinusAsset,
  "magnifying-glass-plus": StrokeMagnifyingGlassPlusAsset,
  mic: StrokeMicAsset,
  microchip: StrokeMicrochipAsset,
  minus: StrokeMinusAsset,
  "minus-circle": StrokeMinusCircleAsset,
  note: StrokeNoteAsset,
  "paint-roller": StrokePaintRollerAsset,
  palette: StrokePaletteAsset,
  paperclip: StrokePaperclipAsset,
  paperplane: StrokePaperplaneAsset,
  pause: StrokePauseAsset,
  pencil: StrokePencilAsset,
  "pencil-square": StrokePencilSquareAsset,
  people: StrokePeopleAsset,
  person: StrokePersonAsset,
  "person-circle": StrokePersonCircleAsset,
  pin: StrokePinAsset,
  play: StrokePlayAsset,
  plus: StrokePlusAsset,
  "plus-circle": StrokePlusCircleAsset,
  "pulse-circle": StrokePulseCircleAsset,
  "puzzle-piece": StrokePuzzlePieceAsset,
  "qr-code": StrokeQrCodeAsset,
  "question-circle": StrokeQuestionCircleAsset,
  "quote-left": StrokeQuoteLeftAsset,
  repeat: StrokeRepeatAsset,
  reply: StrokeReplyAsset,
  robot: StrokeRobotAsset,
  "scales-of-justice": StrokeScalesOfJusticeAsset,
  "seal-check": StrokeSealCheckAsset,
  "share-network": StrokeShareNetworkAsset,
  shield: StrokeShieldAsset,
  "skip-backward": StrokeSkipBackwardAsset,
  "skip-forward": StrokeSkipForwardAsset,
  "smiley-happy": StrokeSmileyHappyAsset,
  sparkles: StrokeSparklesAsset,
  star: StrokeStarAsset,
  stop: StrokeStopAsset,
  strikethrough: StrokeStrikethroughAsset,
  sun: StrokeSunAsset,
  tag: StrokeTagAsset,
  "text-b": StrokeTextBAsset,
  "text-i": StrokeTextIAsset,
  "text-t": StrokeTextTAsset,
  translate: StrokeTranslateAsset,
  "trending-up": StrokeTrendingUpAsset,
  trophy: StrokeTrophyAsset,
  "volume-2": StrokeVolume2Asset,
  wrench: StrokeWrenchAsset,
  x: StrokeXAsset,
  "x-hexagon": StrokeXHexagonAsset,
} as const;

export const filledIconComponents = {
  "arrow-rotate-ccw-up": FilledArrowRotateCcwUpAsset,
  bell: FilledBellAsset,
  bin: FilledBinAsset,
  book: FilledBookAsset,
  "chat-bubble": FilledChatBubbleAsset,
  "chat-bubbles": FilledChatBubblesAsset,
  cloud: FilledCloudAsset,
  headphones: FilledHeadphonesAsset,
  "magnifying-glass": FilledMagnifyingGlassAsset,
  "pencil-square": FilledPencilSquareAsset,
  person: FilledPersonAsset,
  stop: FilledStopAsset,
} as const;

export const strokeIconImages = {
  "arrow-left": require("../../../assets/icons/mishanaer/stroke-png/arrow-left.png"),
  "arrow-right": require("../../../assets/icons/mishanaer/stroke-png/arrow-right.png"),
  "arrow-to-line-down": require("../../../assets/icons/mishanaer/stroke-png/arrow-to-line-down.png"),
  bell: require("../../../assets/icons/mishanaer/stroke-png/bell.png"),
  bin: require("../../../assets/icons/mishanaer/stroke-png/bin.png"),
  book: require("../../../assets/icons/mishanaer/stroke-png/book.png"),
  bookmark: require("../../../assets/icons/mishanaer/stroke-png/bookmark.png"),
  "books-spines": require("../../../assets/icons/mishanaer/stroke-png/books-spines.png"),
  "chart-bar": require("../../../assets/icons/mishanaer/stroke-png/chart-bar.png"),
  camera: require("../../../assets/icons/mishanaer/stroke-png/camera.png"),
  "chat-bubble": require("../../../assets/icons/mishanaer/stroke-png/chat-bubble.png"),
  check: require("../../../assets/icons/mishanaer/stroke-png/check.png"),
  "chevron-left": require("../../../assets/icons/mishanaer/stroke-png/chevron-left.png"),
  "chevron-right": require("../../../assets/icons/mishanaer/stroke-png/chevron-right.png"),
  clipboard: require("../../../assets/icons/mishanaer/stroke-png/clipboard.png"),
  cloud: require("../../../assets/icons/mishanaer/stroke-png/cloud.png"),
  diamond: require("../../../assets/icons/mishanaer/stroke-png/diamond.png"),
  "dots-three-horizontal": require("../../../assets/icons/mishanaer/stroke-png/dots-three-horizontal.png"),
  eye: require("../../../assets/icons/mishanaer/stroke-png/eye.png"),
  "file-txt": require("../../../assets/icons/mishanaer/stroke-png/file-txt.png"),
  folder: require("../../../assets/icons/mishanaer/stroke-png/folder.png"),
  gear: require("../../../assets/icons/mishanaer/stroke-png/gear.png"),
  globe: require("../../../assets/icons/mishanaer/stroke-png/globe.png"),
  "grid-2x2": require("../../../assets/icons/mishanaer/stroke-png/grid-2x2.png"),
  hand: require("../../../assets/icons/mishanaer/stroke-png/hand.png"),
  headphones: require("../../../assets/icons/mishanaer/stroke-png/headphones.png"),
  image: require("../../../assets/icons/mishanaer/stroke-png/image.png"),
  link: require("../../../assets/icons/mishanaer/stroke-png/link.png"),
  list: require("../../../assets/icons/mishanaer/stroke-png/list.png"),
  "lock-locked": require("../../../assets/icons/mishanaer/stroke-png/lock-locked.png"),
  "magnifying-glass": require("../../../assets/icons/mishanaer/stroke-png/magnifying-glass.png"),
  mic: require("../../../assets/icons/mishanaer/stroke-png/mic.png"),
  minus: require("../../../assets/icons/mishanaer/stroke-png/minus.png"),
  note: require("../../../assets/icons/mishanaer/stroke-png/note.png"),
  palette: require("../../../assets/icons/mishanaer/stroke-png/palette.png"),
  paperclip: require("../../../assets/icons/mishanaer/stroke-png/paperclip.png"),
  paperplane: require("../../../assets/icons/mishanaer/stroke-png/paperplane.png"),
  pause: require("../../../assets/icons/mishanaer/stroke-png/pause.png"),
  pencil: require("../../../assets/icons/mishanaer/stroke-png/pencil.png"),
  "pencil-square": require("../../../assets/icons/mishanaer/stroke-png/pencil-square.png"),
  people: require("../../../assets/icons/mishanaer/stroke-png/people.png"),
  person: require("../../../assets/icons/mishanaer/stroke-png/person.png"),
  pin: require("../../../assets/icons/mishanaer/stroke-png/pin.png"),
  play: require("../../../assets/icons/mishanaer/stroke-png/play.png"),
  plus: require("../../../assets/icons/mishanaer/stroke-png/plus.png"),
  "pulse-circle": require("../../../assets/icons/mishanaer/stroke-png/pulse-circle.png"),
  "question-circle": require("../../../assets/icons/mishanaer/stroke-png/question-circle.png"),
  repeat: require("../../../assets/icons/mishanaer/stroke-png/repeat.png"),
  reply: require("../../../assets/icons/mishanaer/stroke-png/reply.png"),
  "share-network": require("../../../assets/icons/mishanaer/stroke-png/share-network.png"),
  "skip-backward": require("../../../assets/icons/mishanaer/stroke-png/skip-backward.png"),
  "skip-forward": require("../../../assets/icons/mishanaer/stroke-png/skip-forward.png"),
  "smiley-happy": require("../../../assets/icons/mishanaer/stroke-png/smiley-happy.png"),
  sparkles: require("../../../assets/icons/mishanaer/stroke-png/sparkles.png"),
  stop: require("../../../assets/icons/mishanaer/stroke-png/stop.png"),
  "text-t": require("../../../assets/icons/mishanaer/stroke-png/text-t.png"),
  translate: require("../../../assets/icons/mishanaer/stroke-png/translate.png"),
  "volume-2": require("../../../assets/icons/mishanaer/stroke-png/volume-2.png"),
  x: require("../../../assets/icons/mishanaer/stroke-png/x.png"),
} as const satisfies Record<string, ImageSourcePropType>;

export const filledIconImages = {
  "arrow-rotate-ccw-up": require("../../../assets/icons/mishanaer/filled-png/arrow-rotate-ccw-up.png"),
  bell: require("../../../assets/icons/mishanaer/filled-png/bell.png"),
  bin: require("../../../assets/icons/mishanaer/filled-png/bin.png"),
  book: require("../../../assets/icons/mishanaer/filled-png/book.png"),
  "chat-bubble": require("../../../assets/icons/mishanaer/filled-png/chat-bubble.png"),
  "chat-bubbles": require("../../../assets/icons/mishanaer/filled-png/chat-bubbles.png"),
  cloud: require("../../../assets/icons/mishanaer/filled-png/cloud.png"),
  headphones: require("../../../assets/icons/mishanaer/filled-png/headphones.png"),
  "magnifying-glass": require("../../../assets/icons/mishanaer/filled-png/magnifying-glass.png"),
  "pencil-square": require("../../../assets/icons/mishanaer/filled-png/pencil-square.png"),
  person: require("../../../assets/icons/mishanaer/filled-png/person.png"),
  stop: require("../../../assets/icons/mishanaer/filled-png/stop.png"),
} as const satisfies Record<string, ImageSourcePropType>;
