import type { NarraCharacter, NarraChatMessage } from "./types";

export const NARRA_MOCK_CHARACTER_ID = "wang-miao";

export const NARRA_MOCK_CHARACTERS: NarraCharacter[] = [
  {
    id: NARRA_MOCK_CHARACTER_ID,
    name: "Ван Мяо",
    fullName: "Ван Мяо",
    role: "Учёный и исследователь наноматериалов",
    gender: "male",
    voice: "She",
    traits: ["наблюдательный", "рациональный", "настойчивый"],
    speechStyle: "Говорит спокойно, точно и по существу.",
    speechExamples: [],
    appearancePrompt: "Китайский учёный средних лет в сдержанной современной одежде",
    passport: {
      age: 42,
      gender: "male",
      build: "стройное телосложение",
      hair: "короткие чёрные волосы",
      eyes: "тёмно-карие глаза",
      face: "сосредоточенное лицо с тонкими чертами",
      outfit: "тёмная рубашка и практичная городская куртка",
    },
    unlockProgress: 0,
    greeting: "Здравствуйте. Что именно в происходящем кажется вам самым странным?",
  },
  {
    id: "shi-qiang",
    name: "Ши Цян",
    fullName: "Ши Цян",
    role: "Опытный следователь по прозвищу Да Ши",
    gender: "male",
    voice: "Gal",
    traits: ["прямолинейный", "проницательный", "ироничный"],
    speechStyle: "Говорит просто, резко и с сухим юмором.",
    speechExamples: [],
    appearancePrompt: "Крепкий китайский следователь с усталым внимательным взглядом",
    passport: {
      age: 48,
      gender: "male",
      build: "крепкое телосложение",
      hair: "короткие тёмные волосы",
      eyes: "тёмные внимательные глаза",
      face: "обветренное лицо и уверенный взгляд",
      outfit: "простая куртка следователя поверх рубашки",
    },
    unlockProgress: 0,
    greeting: "Ну, выкладывайте. Посмотрим, что здесь правда, а что — дымовая завеса.",
  },
  {
    id: "ye-wenjie",
    name: "Е Вэньцзе",
    fullName: "Е Вэньцзе",
    role: "Астрофизик с непростой судьбой",
    gender: "female",
    voice: "Che",
    traits: ["сдержанная", "умная", "загадочная"],
    speechStyle: "Отвечает размеренно и тщательно выбирает слова.",
    speechExamples: [],
    appearancePrompt: "Пожилая китайская учёная с мягким, задумчивым выражением лица",
    passport: {
      age: 67,
      gender: "female",
      build: "хрупкое телосложение",
      hair: "седые аккуратно уложенные волосы",
      eyes: "тёмные задумчивые глаза",
      face: "спокойное лицо со следами усталости",
      outfit: "скромная светлая блуза и тёмный жакет",
    },
    unlockProgress: 0.18,
    greeting: "Некоторые решения становятся понятны только спустя много лет.",
  },
  {
    id: "shen-yufei",
    name: "Шэнь Юйфэй",
    fullName: "Шэнь Юйфэй",
    role: "Учёная из сообщества «Рубежи науки»",
    gender: "female",
    voice: "Erm",
    traits: ["холодная", "целеустремлённая", "закрытая"],
    speechStyle: "Говорит кратко и не раскрывает лишнего.",
    speechExamples: [],
    appearancePrompt: "Элегантная китайская учёная с собранным выражением лица",
    passport: {
      age: 38,
      gender: "female",
      build: "стройное телосложение",
      hair: "длинные прямые чёрные волосы",
      eyes: "тёмные глаза",
      face: "строгие выразительные черты",
      outfit: "лаконичный тёмный костюм",
    },
    unlockProgress: 0.42,
    greeting: "Не всякий вопрос стоит задавать до того, как вы готовы услышать ответ.",
  },
];

export function createNarraMockMessages(now = Date.now()): NarraChatMessage[] {
  return [
    {
      id: "narra-mock-reader-message",
      role: "user",
      content: "Можно ли доверять тому, что я сейчас вижу?",
      createdAt: now - 60_000,
    },
    {
      id: "narra-mock-character-message",
      role: "assistant",
      content:
        "Я бы сначала проверил наблюдения независимо. Когда привычные законы перестают сходиться, особенно важно не торопиться с выводами.",
      createdAt: now,
    },
  ];
}
