import assert from 'node:assert/strict'
import test from 'node:test'
import { createBookObjectStorage } from '../book-object-storage.mjs'

const HASH = 'a'.repeat(64)

test('object storage readiness verifies access to the configured bucket', async () => {
  let command
  const storage = createBookObjectStorage({
    client: {
      async send(candidate) {
        command = candidate
        return {}
      }
    },
    bucket: 'readany-books'
  })
  assert.deepEqual(await storage.checkReady(), { ready: true })
  assert.equal(command.input.Bucket, 'readany-books')
})

test('object storage signs checksum-bound uploads and verifies the provider checksum', async () => {
  const commands = []
  let signingOptions
  const client = {
    async send(command) {
      commands.push(command)
      return {
        ContentLength: 128,
        ContentType: 'application/epub+zip',
        ChecksumSHA256: Buffer.from(HASH, 'hex').toString('base64'),
        Metadata: { content_sha256: HASH }
      }
    }
  }
  const storage = createBookObjectStorage({
    client,
    bucket: 'readany-books',
    async getSignedUrlImpl(_client, command, options) {
      commands.push(command)
      signingOptions = options
      return `https://storage.example/${options.expiresIn}`
    }
  })
  const upload = await storage.createUpload({
    objectKey: 'books/catalog/book/hash/source',
    contentSha256: HASH,
    mimeType: 'application/epub+zip',
    byteSize: 128
  })
  assert.equal(upload.method, 'PUT')
  assert.equal(upload.headers['x-amz-checksum-sha256'], Buffer.from(HASH, 'hex').toString('base64'))
  assert.equal(commands[0].input.ChecksumSHA256, upload.headers['x-amz-checksum-sha256'])
  assert.equal(signingOptions.signableHeaders.has('content-type'), true)
  assert.equal(signingOptions.unhoistableHeaders.has('x-amz-checksum-sha256'), true)
  assert.deepEqual(await storage.verifyUpload({
    objectKey: 'books/catalog/book/hash/source',
    contentSha256: HASH,
    mimeType: 'application/epub+zip',
    byteSize: 128
  }), { verified: true })
})

test('object storage rejects an upload whose bytes do not match the binding', async () => {
  const storage = createBookObjectStorage({
    client: {
      async send() {
        return {
          ContentLength: 127,
          ContentType: 'application/epub+zip',
          Metadata: { content_sha256: HASH }
        }
      }
    },
    bucket: 'readany-books'
  })
  await assert.rejects(() => storage.verifyUpload({
    objectKey: 'books/catalog/book/hash/source',
    contentSha256: HASH,
    mimeType: 'application/epub+zip',
    byteSize: 128
  }), (error) => error.code === 'UPLOAD_INTEGRITY' && error.status === 409)
})

test('object storage never treats client-controlled metadata as a verified checksum', async () => {
  const storage = createBookObjectStorage({
    client: {
      async send() {
        return {
          ContentLength: 128,
          ContentType: 'application/epub+zip',
          Metadata: { content_sha256: HASH }
        }
      }
    },
    bucket: 'readany-books'
  })
  await assert.rejects(() => storage.verifyUpload({
    objectKey: 'books/catalog/book/hash/source',
    contentSha256: HASH,
    mimeType: 'application/epub+zip',
    byteSize: 128
  }), (error) => error.code === 'UPLOAD_INTEGRITY')
})

test('object storage signs short-lived downloads without exposing object keys to clients', async () => {
  let command
  const storage = createBookObjectStorage({
    client: { async send() { return {} } },
    bucket: 'readany-books',
    async getSignedUrlImpl(_client, candidate) {
      command = candidate
      return 'https://storage.example/signed'
    }
  })
  const result = await storage.createDownload({
    objectKey: 'books/catalog/book/media/portrait',
    mimeType: 'image/png',
    filename: 'portrait.png'
  })
  assert.equal(result.url, 'https://storage.example/signed')
  assert.equal(command.input.Key, 'books/catalog/book/media/portrait')
  assert.match(command.input.ResponseContentDisposition, /filename\*=UTF-8/)
})

test('object storage reads bounded objects and writes generated bytes with a checksum', async () => {
  const commands = []
  const storage = createBookObjectStorage({
    client: {
      async send(command) {
        commands.push(command)
        if (commands.length === 1) {
          return {
            ContentLength: 5,
            ContentType: 'text/plain',
            Body: { async transformToByteArray() { return new TextEncoder().encode('hello') } }
          }
        }
        return {}
      }
    },
    bucket: 'readany-books'
  })
  const downloaded = await storage.getBytes({ objectKey: 'books/private/source.txt', maxBytes: 10 })
  assert.equal(downloaded.bytes.toString('utf8'), 'hello')
  const uploaded = await storage.putBytes({
    objectKey: 'generated/private/portrait.png',
    bytes: Buffer.from('image'),
    mimeType: 'image/png'
  })
  assert.equal(uploaded.byteSize, 5)
  assert.match(uploaded.contentHash, /^[0-9a-f]{64}$/)
  assert.equal(commands[1].input.ChecksumSHA256, Buffer.from(uploaded.contentHash, 'hex').toString('base64'))
})

test('object storage refuses to buffer an oversized object', async () => {
  const storage = createBookObjectStorage({
    client: {
      async send() {
        return { ContentLength: 11, Body: Buffer.from('hello world') }
      }
    },
    bucket: 'readany-books'
  })
  await assert.rejects(
    () => storage.getBytes({ objectKey: 'books/private/source.txt', maxBytes: 10 }),
    /allowed read size/
  )
})

test('object storage deletes generated materials in one explicit batch', async () => {
  let command
  const storage = createBookObjectStorage({
    client: { async send(candidate) { command = candidate; return {} } },
    bucket: 'readany-books'
  })
  assert.deepEqual(await storage.deleteObjects([
    'generated/private/portrait.png',
    'generated/private/voice.mp3',
    'generated/private/portrait.png'
  ]), { deleted: 2 })
  assert.deepEqual(command.input.Delete.Objects, [
    { Key: 'generated/private/portrait.png' },
    { Key: 'generated/private/voice.mp3' }
  ])
})
