CREATE TABLE IF NOT EXISTS catalog_book_popularity (
  source_key TEXT PRIMARY KEY,
  popularity_rank INTEGER NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT catalog_book_popularity_source_key_check
    CHECK (source_key ~ '^[a-z0-9][a-z0-9-]*$'),
  CONSTRAINT catalog_book_popularity_rank_check
    CHECK (popularity_rank > 0)
);

CREATE INDEX IF NOT EXISTS catalog_book_popularity_rank_index
  ON catalog_book_popularity (popularity_rank, source_key);

-- Complete order from "полный-каталог-512-книг.md" next to narra-books-ru-fixed.
-- source_key is the EPUB filename without its extension. WITH ORDINALITY makes
-- the array position the catalog popularity rank (1 is the most popular).
WITH ranking AS (
  SELECT source_key, ordinality::integer AS popularity_rank
  FROM unnest(ARRAY[
    'vojna-i-mir-tolstoj',
    'prestuplenie-i-nakazanie',
    'anna-karenina',
    'evgenij-onegin',
    'bratya-karamazovy',
    'mertvye-dushi-tom-pervyj',
    'geroj-nashego-vremeni',
    'idiot',
    'gamlet-princ-datskij',
    'gore-ot-uma',
    'oblomov',
    'otcy-i-deti',
    'revizor',
    'kapitanskaya-dochka',
    'besy',
    'dubrovskij',
    'romeo-i-dzhuletta',
    'vishnevyj-sad',
    'pikovaya-dama',
    'faust',
    'groza',
    'dvenadcat-stulev',
    'chajka',
    'zolotoj-telenok',
    'otverzhennye',
    'taras-bulba',
    'martin-iden',
    'shinel',
    'alye-parusa',
    'vij',
    'belaya-gvardiya',
    'robinzon-kruzo',
    'dama-s-sobachkoj',
    'dvadcat-tysyach-le-pod-vodoj',
    'dyadya-vanya',
    'na-dne',
    'tri-sestry',
    'voskresenie',
    'granatovyj-braslet',
    'deti-kapitana-granta',
    'levsha',
    'mumu',
    'portret-doriana-greya',
    'temnye-allei',
    'ajvengo',
    'belye-nochi',
    'gospozha-bovari',
    'olesya',
    'gospodin-iz-san-francisko',
    'zov-predkov',
    'igrok',
    'kashtanka',
    'mcyri',
    'nos',
    'smert-ivana-ilicha',
    'staruha-izergil',
    'chelovek-amfibiya',
    'demon',
    'ledi-makbet-mcenskogo-uezda',
    'pervaya-lyubov',
    'boris-godunov',
    'asya',
    'detstvo',
    'dvoryanskoe-gnezdo',
    'zapiski-iz-podpolya',
    'ionych',
    'nedorosl',
    'ocharovannyj-strannik',
    'rokovye-yajca',
    'unizhennye-i-oskorblennye',
    'giperboloid-inzhenera-garina',
    'bednye-lyudi',
    'gospoda-golovlevy',
    'detstvo-tolstoj',
    'duel',
    'zapiski-iz-mertvogo-doma',
    'zapiski-sumasshedshego',
    'kavkazskij-plennik-tolstoj',
    'korol-lir',
    'morskoj-volk',
    'povesti-pokojnogo-ivana-petrovicha-belkina',
    'podrostok',
    'poedinok',
    'puteshestviya-lemyuelya-gullivera',
    'step',
    'chto-delat',
    'istoriya-odnogo-goroda',
    'komu-na-rusi-zhit-horosho',
    'mednyj-vsadnik',
    'antonovskie-yabloki',
    'aelita',
    'dushechka',
    'krejcerova-sonata',
    'morfij',
    'nakanune',
    'portret',
    'rudin',
    'hadzhi-murat',
    'ruslan-i-lyudmila',
    'ariel',
    'beguschaya-po-volnam',
    'borba-mirov',
    'dvojnik',
    'kazaki',
    'meschanin-vo-dvoryanstve',
    'nevskij-prospekt',
    'obyknovennaya-istoriya',
    'otec-sergij',
    'princ-i-nischij',
    'ubijstvo-na-ulice-morg',
    'chelkash',
    'shagrenevaya-kozha',
    'yama',
    'venecianskij-kupec',
    'belyj-pudel',
    'veshnie-vody',
    'zolotoj-zhuk',
    'krotkaya',
    'obryv',
    'starosvetskie-pomeschiki',
    'chernyj-monah',
    'iliada',
    'poltava',
    'banya',
    'v-lyudyah',
    'dom-s-mezoninom',
    'dym',
    'dyavoliada',
    'dyadyushkin-son',
    'zhenitba',
    'zhivoj-trup',
    'zolotoj-klyuchik',
    'klop',
    'kopi-carya-solomona',
    'mat',
    'otrochestvo',
    'povest-o-tom-kak-possorilsya-ivan-ivanovich-s-ivanom-nikiforovichem',
    'selo-stepanchikovo-i-ego-obitateli',
    'yulij-cezar',
    'son-smeshnogo-cheloveka',
    'oblako-v-shtanah',
    'slovo-o-polku-igoreve',
    'evgeniya-grande',
    'netochka-nezvanova',
    'skupoj',
    'usmirenie-svoenravnoj',
    'anna-snegina',
    'moroz-krasnyj-nos',
    'vechnyj-muzh',
    'iuda-iskariot',
    'knyaz-serebryanyj',
    'kukolnyj-dom',
    'maskarad',
    'melkij-bes',
    'mesyac-v-derevne',
    'meschane',
    'moloh',
    'richard-iii',
    'skazka-o-care-saltane',
    'skuchnaya-istoriya',
    'holstomer',
    'russkie-zhenschiny',
    'yunost',
    'arap-petra-velikogo',
    'burya',
    'byloe-i-dumy',
    'v-ovrage',
    'derevnya',
    'zhizn',
    'kroshka-dorrit',
    'leto-gospodne',
    'moi-universitety',
    'moya-zhizn',
    'nov',
    'muzhiki',
    'snezhnaya-koroleva',
    'nevesta',
    'foma-gordeev',
    'bahchisarajskij-fontan',
    'gambrinus',
    'delo-artamonovyh',
    'zapechatlennyj-angel',
    'kavkazskij-plennik',
    'kolodec-i-mayatnik',
    'mizantrop',
    'rasskaz-o-semi-poveshennyh',
    'salambo',
    'svadba-krechinskogo',
    'suhodol',
    'timur-i-ego-komanda',
    'tri-goda',
    'fregat-pallada',
    'hozyajka',
    'schelkunchik-i-myshinyj-korol',
    'alenkij-cvetochek',
    'dachniki',
    'drama-na-ohote',
    'zvezda-kec',
    'igroki',
    'kventin-dorvard',
    'krasnyj-cvetok',
    'kto-vinovat',
    'rusalochka',
    'semejnoe-schastie',
    'skvernyj-anekdot',
    'sny-changa',
    'sulamif',
    'uchitel-slovesnosti',
    'chapaev',
    'don-zhuan',
    'pesnya-pro-carya-ivana-vasilevicha-molodogo-oprichnika-i-udalogo-kupca',
    'arhierej',
    'blistayuschij-mir',
    'dnevnik-lishnego-cheloveka',
    'zhitejskie-vozzreniya-kota-murra',
    'konek-gorbunok',
    'peterburgskie-truschoby',
    'prodavec-vozduha',
    'salomeya',
    'slaboe-serdce',
    'slon',
    'stepnoj-korol-lir',
    'tupejnyj-hudozhnik',
    'chuk-i-gek',
    'dva-gusara',
    'deti-podzemelya',
    'deti-solnca',
    'dyavol',
    'zheleznaya-volya',
    'zolotaya-cep',
    'zolotoj-gorshok',
    'knyaginya-ligovskaya',
    'krasnyj-smeh',
    'leshij',
    'misteriya-buff',
    'nahlebnik',
    'ognennyj-angel',
    'pesn-torzhestvuyuschej-lyubvi',
    'privalovskie-milliony',
    'silna-kak-smert',
    'upyr',
    'falshivyj-kupon',
    'cusima',
    'shkola',
    'delo',
    'zatishe',
    'ledyanoj-dom',
    'rasskaz-neizvestnogo-cheloveka',
    'tot-kto-poluchaet-poschechiny',
    'troe',
    'chernaya-kurica-ili-podzemnye-zhiteli',
    'edip-v-kolone',
    'egipetskie-nochi',
    'korobejniki',
    'brigadir',
    'varvary',
    'doroga-v-nikuda',
    'zhizn-vasiliya-fivejskogo',
    'zhitie-odnoj-baby',
    'zapiski-vracha',
    'konovalov',
    'listrigony',
    'malva',
    'narodnye-russkie-skazki',
    'ogni',
    'ocherki-bursy',
    'sanin',
    'smert-tarelkina',
    'sovremennaya-idilliya',
    'soroka-vorovka',
    'utro-pomeschika',
    'uchitel-fehtovaniya',
    'shtabs-kapitan-rybnikov',
    'pugachev',
    'byvshie-lyudi',
    'detstvo-temy',
    'dikie-lebedi',
    'nadezhda-nikolaevna',
    'polikushka',
    'yurij-miloslavskij-ili-russkie-v-1612-godu',
    'krysolov',
    'smert-ioanna-groznogo',
    'voskresshie-bogi-leonardo-da-vinchi',
    'zhizn-cheloveka',
    'krysolov-grin',
    'na-krayu-sveta',
    'skazki',
    'odnodum',
    'solnce-mertvyh',
    'son-makara',
    'suprugi-orlovy',
    'domik-v-kolomne',
    'kain',
    'roza-i-krest',
    'horosho',
    'knyazhna-tarakanova',
    'nesmertelnyj-golovan',
    'rozhdennye-burej',
    'seraya-shejka',
    'smert-bogov-yulian-otstupnik',
    'vladimir-ilich-lenin',
    'manfred',
    'gimnazisty',
    'gubernator',
    'dzhessi-i-morgiana',
    'dnevnik-foksa-mikki',
    'zheleznyj-potok',
    'zhenskaya-vojna',
    'zoloto',
    'maksimka',
    'master-ballantre',
    'molotov',
    'pompadury-i-pompadurshi',
    'chelovek-iz-restorana',
    'chelovek-nashedshij-svoe-lico',
    '150-000-000',
    'vozmezdie',
    'satiry',
    'dni-nashej-zhizni',
    'zahudalyj-rod',
    'petr-i-aleksej',
    'pohozhdeniya-nevzorova-ili-ibikus',
    'boyarin-orsha',
    'sasha',
    'izmail-bej',
    'strana-negodyaev',
    'car-boris',
    'chelovek',
    'bez-yazyka',
    'za-rubezhom',
    'knyazhna-dzhavaha',
    'sashka-zhegulev',
    'svetlaya-lichnost',
    'soki-zemli',
    'studenty',
    'chudesnoe-oko',
    'vojna-i-mir',
    'car-devica',
    'vadim',
    'zapiski-institutki',
    'kolomba',
    'nekuda',
    'palata-6',
    'pod-nebom-arktiki',
    'tajna-korablya',
    'podvodnye-zemledelcy',
    'emigranty',
    'dalnie-strany',
    'inzhenery',
    'meschanskoe-schaste',
    'na-nozhah',
    'klara-milich',
    'razin-stepan',
    'serebryanyj-golub',
    'sibirochka',
    'stranica-lyubvi',
    'hromoj-barin',
    'neschastnye',
    'andzhelo',
    'ioann-damaskin',
    'molodec',
    'askoldova-mogila',
    'zapiski-malenkoj-gimnazistki',
    'istoriya-lyubovnaya',
    'krugi-po-vode',
    'chudaki',
    'vokrug-sveta-na-korshune',
    'myatezh',
    'na-perelome',
    'princ-otto',
    'hleb',
    'mik',
    'sovremenniki',
    '14-dekabrya',
    'bednost-ne-porok',
    'aleksandr-i',
    'bez-viny-vinovatye',
    'v-tupike',
    'bespridannica',
    'gornoe-gnezdo',
    'beshenye-dengi',
    'dalnejshie-priklyucheniya-robinzona-kruzo',
    'volki-i-ovcy',
    'dred-ili-povest-o-proklyatom-bolote',
    'goryachee-serdce',
    'knyazhna-mimi',
    'dohodnoe-mesto',
    'kotik-letaev',
    'les',
    'malysh',
    'na-vsyakogo-mudreca-dovolno-prostoty',
    'obojdennye',
    'pisma-starka-monro',
    'povesti',
    'poslednij-novik',
    'roslavlev-ili-russkie-v-1812-godu',
    'svoi-lyudi-sochtemsya',
    'sevastopolskij-malchik',
    'snegurochka',
    'sozhzhennaya-moskva',
    'talanty-i-poklonniki',
    'basurman',
    'malenkij-chelovek',
    'mertvoe-ozero',
    's-togo-berega',
    'silfida',
    'skazka-bochki',
    'nal-i-damayanti',
    'knyazhna-zizi',
    'mirovich',
    'pochta-duhov-ili-uchenaya-nravstvennaya-i-kriticheskaya-perepiska-arab',
    'russkie-nochi',
    'sestry',
    'vojnarovskij',
    'krasavice-kotoraya-nyuhala-tabak',
    'bez-dorogi',
    'kosmorama',
    'moskva-pod-udarom',
    'nevesta-solnca',
    'soldaty',
    'brynskij-les',
    'dedy',
    'detskie-gody-bagrova-vnuka',
    'zhizn-i-pohozhdeniya-tihona-trostnikova',
    'moskovskij-chudak',
    'numa-rumestan',
    'rannie-vshody',
    'salamandra',
    'semejnaya-hronika',
    'tonkij-chelovek-ego-priklyucheniya-i-nablyudeniya',
    'kulak',
    'beglye-v-novorossii',
    'v-sutoloke-provincialnoj-zhizni',
    'zimove-na-studenoj',
    'peski',
    'boyarschina',
    'vasilij-terkin',
    'egor-abozov',
    'za-chto',
    'iskusitel',
    'meschane-pisemskij',
    'novye-sily',
    'russkie-v-nachale-osmnadcatogo-stoletiya',
    'smelaya-zhizn',
    'tamara-bendavid',
    'tyazhelye-sny',
    'tma-egipetskaya',
    'dnevnik-seminarista',
    'altar-pobedy',
    'v-vodovorote',
    'volya',
    'dvenadcatyj-god',
    'kapli-krovi',
    'kitaj-gorod',
    'monastyrka',
    'potemkin-na-dunae',
    'prolog',
    'sergej-gorbatov',
    'torzhestvo-vaala',
    'dopolneniya-k-peterburgu',
    'bez-ishoda',
    'velikij-rozenkrejcer',
    'v-mutnoj-vode',
    'vzbalamuchennoe-more',
    'volteryanec',
    'zhertva-vechernyaya',
    'volhvy',
    'zhrecy',
    'knyazhna-ostrozhskaya',
    'koroleva-ortruda',
    'lesovichka',
    'nashi-nravy',
    'alferev',
    'vnuchka-pancirnogo-boyarina',
    'vtoraya-nina',
    'gospodin-velikij-novgorod',
    'kapitan-grenaderskoj-roty',
    'kapitan-pervogo-ranga',
    'karera-strukova',
    'kasimovskaya-nevesta',
    'otbleski-siyaniya',
    'solenaya-kupel',
    'povesti-v-povesti',
    'starshiny-vilbajskoj-shkol',
    'staryj-dom',
    'car-petr-i-pravitelnica-sofya',
    'yunyj-imperator',
    'ammalat-bek',
    'velikij-raskol',
    'groznaya-druzhina',
    'derzhavnyj-plotnik',
    'zhenih-carevny',
    'zamurovannaya-carica',
    'izgnannik',
    'lyusina-zhizn',
    'morehod-nikitin',
    'pazh-cesarevny',
    'naezdy',
    'pereselency',
    'poslednie-gorbatovy',
    'priyutki',
    'stranniki',
    'strashnoe-gadane',
    'carskoe-posolstvo',
    'fregat-nadezhda',
    'car-i-getman',
    'nravy-rasteryaevoj-ulicy',
    'velmozhnaya-panna',
    'ee-velichestvo-lyubov',
    'irod',
    'solnce-vstanet',
    'ten-iroda'
  ]::text[]) WITH ORDINALITY AS value(source_key, ordinality)
)
INSERT INTO catalog_book_popularity (source_key, popularity_rank)
SELECT source_key, popularity_rank
FROM ranking;

-- Older catalog imports used human-assigned catalog keys instead of the EPUB
-- filename. Keep those stable public keys and map them to the same ranking.
CREATE TABLE catalog_book_popularity_aliases (
  catalog_key TEXT PRIMARY KEY,
  source_key TEXT NOT NULL REFERENCES catalog_book_popularity(source_key)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX catalog_book_popularity_aliases_source_key_index
  ON catalog_book_popularity_aliases (source_key, catalog_key);

INSERT INTO catalog_book_popularity_aliases (catalog_key, source_key)
VALUES
  ('crime-and-punishment', 'prestuplenie-i-nakazanie'),
  ('eval-v17-b50-bratya-karamazovy-chast-4', 'bratya-karamazovy'),
  ('eval-v17-b50-mertvye-dushi-tom-pervyj', 'mertvye-dushi-tom-pervyj'),
  ('eval-v14-romeo-i-dzhuletta', 'romeo-i-dzhuletta'),
  ('seagull', 'chajka'),
  ('eval-v14-taras-bulba', 'taras-bulba'),
  ('eval-v14-shinel', 'shinel'),
  ('eval-v17-b50-belaya-gvardiya', 'belaya-gvardiya'),
  ('eval-v14-dama-s-sobachkoj', 'dama-s-sobachkoj'),
  ('eval-v14-na-dne', 'na-dne'),
  ('eval-v17-b50-deti-kapitana-granta', 'deti-kapitana-granta'),
  ('eval-v17-b50-portret-doriana-greya', 'portret-doriana-greya'),
  ('eval-v14-mcyri', 'mcyri'),
  ('eval-v14-nos', 'nos'),
  ('eval-v17-b50-smert-ivana-ilicha', 'smert-ivana-ilicha'),
  ('eval-v17-b50-detstvo', 'detstvo'),
  ('eval-v14-rokovye-yajca', 'rokovye-yajca'),
  ('eval-v17-b50-giperboloid-inzhenera-garina', 'giperboloid-inzhenera-garina'),
  ('eval-v17-b50-detstvo-tolstoj', 'detstvo-tolstoj'),
  ('narra-ru-top100-puteshestviya-gullivera-6c7ea3de', 'puteshestviya-lemyuelya-gullivera'),
  ('eval-v17-b50-chto-delat', 'chto-delat'),
  ('eval-v14-aelita', 'aelita'),
  ('eval-v17-b50-beguschaya-po-volnam', 'beguschaya-po-volnam'),
  ('eval-v17-b50-otec-sergij', 'otec-sergij'),
  ('eval-v17-b50-ubijstvo-na-ulice-morg', 'ubijstvo-na-ulice-morg'),
  ('eval-v17-b50-venecianskij-kupec', 'venecianskij-kupec'),
  ('eval-v14-zhenitba', 'zhenitba'),
  ('eval-v17-b50-otrochestvo', 'otrochestvo'),
  ('eval-v14-oblako-v-shtanah', 'oblako-v-shtanah'),
  ('eval-v17-b50-maskarad', 'maskarad'),
  ('eval-v14-skazka-o-care-saltane', 'skazka-o-care-saltane'),
  ('eval-v17-b50-burya', 'burya'),
  ('eval-v17-b50-moi-universitety', 'moi-universitety'),
  ('narra-ru-038-kavkazskij-plennik-pushkin', 'kavkazskij-plennik'),
  ('eval-v17-b50-schelkunchik-i-myshinyj-korol', 'schelkunchik-i-myshinyj-korol'),
  ('eval-v17-b50-sulamif', 'sulamif'),
  ('eval-v17-b50-chapaev', 'chapaev'),
  ('eval-v17-b50-peterburgskie-truschoby', 'peterburgskie-truschoby'),
  ('eval-v17-b50-tupejnyj-hudozhnik', 'tupejnyj-hudozhnik'),
  ('eval-v17-b50-deti-solnca', 'deti-solnca'),
  ('narra-ru-054-chernaya-kurica', 'chernaya-kurica-ili-podzemnye-zhiteli'),
  ('eval-v17-b50-soroka-vorovka', 'soroka-vorovka'),
  ('eval-v17-b50-pugachev', 'pugachev'),
  ('eval-v17-b50-zhizn-cheloveka', 'zhizn-cheloveka'),
  ('eval-v17-b50-krysolov-grin', 'krysolov-grin'),
  ('eval-v17-b50-skazki', 'skazki'),
  ('eval-v17-b50-horosho', 'horosho'),
  ('eval-v17-b50-zahudalyj-rod', 'zahudalyj-rod'),
  ('eval-v17-b50-chelovek', 'chelovek'),
  ('eval-v17-b50-bez-yazyka', 'bez-yazyka'),
  ('eval-v17-b50-sibirochka', 'sibirochka'),
  ('eval-v17-b50-neschastnye', 'neschastnye'),
  ('eval-v17-b50-hleb', 'hleb'),
  ('eval-v17-b50-roslavlev-ili-russkie-v-1812-godu', 'roslavlev-ili-russkie-v-1812-godu'),
  ('eval-v17-b50-mertvoe-ozero', 'mertvoe-ozero'),
  ('eval-v17-b50-nal-i-damayanti', 'nal-i-damayanti'),
  ('pushkin-krasavitse', 'krasavice-kotoraya-nyuhala-tabak'),
  ('eval-v17-b50-bez-dorogi', 'bez-dorogi'),
  ('eval-v17-b50-moskovskij-chudak', 'moskovskij-chudak'),
  ('eval-v17-b50-salamandra', 'salamandra'),
  ('eval-v17-b50-peski', 'peski'),
  ('eval-v17-b50-za-chto', 'za-chto'),
  ('eval-v17-b50-volteryanec', 'volteryanec'),
  ('eval-v17-b50-vnuchka-pancirnogo-boyarina', 'vnuchka-pancirnogo-boyarina'),
  ('eval-v17-b50-starshiny-vilbajskoj-shkol', 'starshiny-vilbajskoj-shkol'),
  ('eval-v17-b50-izgnannik', 'izgnannik'),
  ('eval-v17-b50-strashnoe-gadane', 'strashnoe-gadane');

-- Preserve every edition, but expose only the newest one when old and new
-- catalog keys resolve to the same ranked book.
WITH ranked_catalog AS (
  SELECT edition.id,
         first_value(edition.id) OVER (
           PARTITION BY popularity.source_key
           ORDER BY edition.created_at DESC, edition.id DESC
         ) AS replacement_id,
         row_number() OVER (
           PARTITION BY popularity.source_key
           ORDER BY edition.created_at DESC, edition.id DESC
         ) AS edition_position
  FROM book_editions AS edition
  LEFT JOIN catalog_book_popularity_aliases AS popularity_alias
    ON popularity_alias.catalog_key = edition.catalog_key
  JOIN catalog_book_popularity AS popularity
    ON popularity.source_key = COALESCE(popularity_alias.source_key, CASE
      WHEN edition.catalog_key ~ '^narra-ru-top100-.+-[0-9a-f]{8}$' THEN
        regexp_replace(
          substr(edition.catalog_key, length('narra-ru-top100-') + 1),
          '-[0-9a-f]{8}$',
          ''
        )
      WHEN edition.catalog_key ~ '^narra-ru-[0-9]+-.+$' THEN
        regexp_replace(edition.catalog_key, '^narra-ru-[0-9]+-', '')
      ELSE edition.catalog_key
    END)
  WHERE edition.scope = 'catalog'
    AND edition.status IN ('base_ready', 'published')
    AND edition.catalog_hidden_at IS NULL
), superseded AS (
  SELECT id, replacement_id
  FROM ranked_catalog
  WHERE edition_position > 1
)
UPDATE book_editions AS edition
SET catalog_hidden_at = now(),
    replaced_by_book_edition_id = superseded.replacement_id,
    updated_at = now()
FROM superseded
WHERE edition.id = superseded.id;
